export const caribbeanCountries = [
  "Bahamas",
  "Barbados",
  "Cuba",
  "Dominican Republic",
  "Haiti",
  "Jamaica",
  "Trinidad and Tobago",
  "Puerto Rico",
  "Antigua and Barbuda",
  "Aruba",
  "Cayman Islands",
  "Curaçao",
  "Dominica",
  "Grenada",
  "Guadeloupe",
  "Martinique",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Sint Maarten",
  "Turks and Caicos Islands",
  "U.S. Virgin Islands"
];