// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vljmxspvxzmduewqzfra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsam14c3B2eHptZHVld3F6ZnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0ODU3MzEsImV4cCI6MjA1MzA2MTczMX0.ymFBAqE1I2RIboeV0YBo3bdHt5d8g0mBCR79Ye7oguQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);