// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjsirxwfceesuqbmixdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqc2lyeHdmY2Vlc3VxYm1peGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0OTA4OTEsImV4cCI6MjA1MzA2Njg5MX0.QcJExcG2LDIy3M-ZI-DLa-6h7Oy4U004D63dI0gmTmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);